import { Product } from "types/product.type";

export const products: Product[] = [
  {
    product_id: "P12345",
    product_name: "Wireless Bluetooth Headphones",
    product_price: 49.99,
    product_image: "https://example.com/images/product1.jpg",
    product_quantity: 150,
    product_description:
      "High-quality wireless Bluetooth headphones with noise cancellation and long battery life.",
    product_category: "Electronics",
    product_stock: 100,
    product_rating: 4.5,
    product_review:
      "Amazing sound quality and comfortable to wear for long hours!",
    product_sold: 350,
    product_discount: 10,
    product_wishlist: 200,
    product_date_added: "2024-12-01",
    product_date_updated: "2024-12-05",
    product_views: 500,
    product_status: "Available",
  },
  {
    product_id: "P12346",
    product_name: "Smartphone Stand",
    product_price: 15.99,
    product_image: "https://example.com/images/product2.jpg",
    product_quantity: 10,
    product_description:
      "Adjustable aluminum smartphone stand, perfect for desks and nightstands.",
    product_category: "Accessories",
    product_stock: 250,
    product_rating: 4.7,
    product_review: "Sturdy and practical for all phone sizes.",
    product_sold: 450,
    product_discount: 5,
    product_wishlist: 150,
    product_date_added: "2024-11-20",
    product_date_updated: "2024-12-02",
    product_views: 650,
    product_status: "Available",
  },
  {
    product_id: "P12347",
    product_name: "LED Desk Lamp",
    product_price: 39.99,
    product_image: "https://example.com/images/product3.jpg",
    product_quantity: 80,
    product_description:
      "Modern LED desk lamp with adjustable brightness and USB charging port.",
    product_category: "Home",
    product_stock: 60,
    product_rating: 4.3,
    product_review: "Excellent lamp with great light control.",
    product_sold: 120,
    product_discount: 15,
    product_wishlist: 120,
    product_date_added: "2024-11-15",
    product_date_updated: "2024-12-03",
    product_views: 300,
    product_status: "Available",
  },
  {
    product_id: "P12348",
    product_name: "Gaming Mouse",
    product_price: 29.99,
    product_image: "https://example.com/images/product4.jpg",
    product_quantity: 200,
    product_description:
      "High-precision gaming mouse with customizable RGB lighting.",
    product_category: "Electronics",
    product_stock: 180,
    product_rating: 4.8,
    product_review: "Fantastic for gaming, responsive and stylish.",
    product_sold: 400,
    product_discount: 10,
    product_wishlist: 300,
    product_date_added: "2024-10-25",
    product_date_updated: "2024-12-04",
    product_views: 800,
    product_status: "Available",
  },
  {
    product_id: "P12349",
    product_name: "Yoga Mat",
    product_price: 25.0,
    product_image: "https://example.com/images/product5.jpg",
    product_quantity: 1,
    product_description:
      "Non-slip yoga mat with excellent grip and cushioning.",
    product_category: "Fitness",
    product_stock: 100,
    product_rating: 4.6,
    product_review: "Perfect for all types of workouts, easy to clean.",
    product_sold: 200,
    product_discount: 8,
    product_wishlist: 180,
    product_date_added: "2024-11-10",
    product_date_updated: "2024-12-03",
    product_views: 400,
    product_status: "Available",
  },
  {
    product_id: "P12350",
    product_name: "Stainless Steel Water Bottle",
    product_price: 19.99,
    product_image: "https://example.com/images/product6.jpg",
    product_quantity: 300,
    product_description:
      "Durable and insulated water bottle, keeps drinks cold for 24 hours.",
    product_category: "Outdoors",
    product_stock: 280,
    product_rating: 4.4,
    product_review: "Great design and keeps water cool for hours.",
    product_sold: 350,
    product_discount: 10,
    product_wishlist: 250,
    product_date_added: "2024-09-15",
    product_date_updated: "2024-12-04",
    product_views: 750,
    product_status: "Available",
  },
  {
    product_id: "P12351",
    product_name: "Wireless Keyboard",
    product_price: 34.99,
    product_image: "https://example.com/images/product7.jpg",
    product_quantity: 90,
    product_description:
      "Slim wireless keyboard with a comfortable typing experience.",
    product_category: "Electronics",
    product_stock: 70,
    product_rating: 4.2,
    product_review: "Lightweight and perfect for work or travel.",
    product_sold: 150,
    product_discount: 12,
    product_wishlist: 180,
    product_date_added: "2024-10-05",
    product_date_updated: "2024-12-02",
    product_views: 350,
    product_status: "Available",
  },
  {
    product_id: "P12352",
    product_name: "Backpack",
    product_price: 59.99,
    product_image: "https://example.com/images/product8.jpg",
    product_quantity: 75,
    product_description:
      "Spacious and durable backpack with multiple compartments for travel.",
    product_category: "Fashion",
    product_stock: 50,
    product_rating: 4.5,
    product_review: "Great for daily use and traveling, very spacious.",
    product_sold: 120,
    product_discount: 20,
    product_wishlist: 100,
    product_date_added: "2024-10-10",
    product_date_updated: "2024-12-01",
    product_views: 400,
    product_status: "Available",
  },
  {
    product_id: "P12353",
    product_name: "Cookware Set",
    product_price: 89.99,
    product_image: "https://example.com/images/product9.jpg",
    product_quantity: 50,
    product_description:
      "Non-stick cookware set with durable aluminum construction.",
    product_category: "Kitchen",
    product_stock: 40,
    product_rating: 4.7,
    product_review: "Perfect for cooking, easy to clean, and high-quality.",
    product_sold: 90,
    product_discount: 18,
    product_wishlist: 110,
    product_date_added: "2024-08-30",
    product_date_updated: "2024-12-02",
    product_views: 300,
    product_status: "Available",
  },
  {
    product_id: "P12354",
    product_name: "Noise-Cancelling Earbuds",
    product_price: 79.99,
    product_image: "https://example.com/images/product10.jpg",
    product_quantity: 1,
    product_description:
      "Compact noise-cancelling earbuds with a sleek design and excellent sound.",
    product_category: "Electronics",
    product_stock: 90,
    product_rating: 4.6,
    product_review: "Superb noise cancellation and sound quality.",
    product_sold: 180,
    product_discount: 12,
    product_wishlist: 230,
    product_date_added: "2024-07-15",
    product_date_updated: "2024-12-04",
    product_views: 900,
    product_status: "Available",
  },
];
